#!/bin/bash
sleep 60
#/usr/bin/epiphany-browser -a --profile .config http://localhost:8000 &
/usr/bin/chromium-browser --kiosk http://localhost/index.html &
xset -dpms # disable DPMS (Energy Star) features.
xset s off # disable screen saver
xset s noblank # don't blank the video device
sleep 5
#/usr/bin/xte 'key F11'
#sleep 5
#/usr/bin/xte 'key F5'
#sleep 5
/usr/bin/xte 'mousemove 1920 1080'
